const ResponseMessage = module.exports = {
    ACCTION_SUCCESSFULLY: 'Action Successfully',
    ACTION_FAILURE: 'Action Failure',
    TOKEN_EXPRIDED: 'Your token was exprided',
    USER_NOTE_ALLOW: 'You do not have access',
    USER_NOTE_AUTHENTICATED: 'You are not authenticated',
    USER_ACCOUNT_EXIST: 'User account already',
    USER_PHONE_EXIST: 'Phone number already',
    PASSWORD_WRONG: 'Wrong password',
    USER_ACCOUNT_NOTREGIS: 'Account not registered',
    USER_ISNOT_ADMIN: 'You are not administrator',
    USER_ISNOT_SALER: 'You are not saler',
    USER_ISNOT_DESIGNER: 'You are not designer',
    ACCOUNT_ISNOT_CUSTOMER: 'This account is not customer',
    UPDATE_SUCCESSFULLY: 'Update successfully',
    PASSWORD_NOTENOUGH: 'Password not enough characters',
    USERNAME_NOTENOUGH: 'Username not enough characters',
    DELETE_USER_ONDESIGN_FAILURE: 'Can not delete this user in a certain Design',
    DELETE_USER_ONSTATISTICKPI_FAILURE: 'Can not delete this user in a certain StatisticKPI',
    ERROR_UPLOAD: 'Error when uploading media file',
    MEDIA_NOTFOUD: 'Media no foud',
    REGISTRY_EMAIL_NOTYET: 'You have not registered email',
}

